# Generated by Django 4.2.3 on 2023-07-29 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
