# Generated by Django 4.2.3 on 2023-07-29 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_rename_update_article_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
