# Generated by Django 4.2.3 on 2023-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_alter_article_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
